name: template-project-ci
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: ESLint Test
        uses: AbdulRehman-1/eslint-action@latest
        with:
          eslint-args: '--ignore-path=.gitignore'
          eslintrc: false
          extensions: 'vue,ts'
          auto-auto-fix-before-test: false
          annotations: true

  cypress-run:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
