name: template-project-ci
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  eslint_check:
    name: ESLint Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "lib, scripts"
        eslintConfig: "myConfigs/eslint.config.js"
        eslintExt: "ts, vue"

  cypress-run:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
